title: Jin-Rou Chang | Mechanical Engineering Portfolio
description: > # this means to ignore newlines until "baseurl:"
 Graduate student at the University of Michigan specializing in Mechanical Design and Robotics.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jrchang330.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jin-Rou Chang # add your name
author-img: Jin-Rou_Chang.jpg # add your photo
about-author: A first-year M.S. student in Mechanical Engineering at the University of Michigan, specializing in Mechanical Design and Robotics. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: JRChang330 # add your Github handle
social-linkedin: jin-rou-chang  # add your Linkedin handle
social-email: jinrou@umich.edu   # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
